[background]
path = "/usr/share/backgrounds/greeter.jpg"
fit = "Cover"

[GTK]
application_prefer_dark_theme = true
font_name = "JetBrainsMono Nerd Font 14"
icon_theme_name = "Yaru-blue"
theme_name = "Adwaita-dark"

[commands]
reboot = ["systemctl", "reboot"]
poweroff = ["systemctl", "poweroff"]

[appearance]
greeting_msg = "Welcome"
